{{-- Deliberately plain HTML with inline styles: Dompdf renders a small subset
     of CSS, and the site stylesheet is written for a browser. --}}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1c1915; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        .muted { color: #6b6259; }
        table { width: 100%; border-collapse: collapse; margin-top: 18px; }
        th, td { text-align: left; padding: 8px 6px; border-bottom: 1px solid #e2dace; }
        td.num, th.num { text-align: right; }
        .totals td { border: 0; padding: 3px 6px; }
        .totals .grand { font-weight: bold; border-top: 1px solid #1c1915; }
        .parties td { vertical-align: top; width: 50%; border: 0; padding: 0 6px 0 0; }
        .foot { margin-top: 28px; font-size: 10px; color: #6b6259; line-height: 1.5; }
    </style>
</head>
<body>
    <h1>{{ __('Invoice') }} {{ $invoice->invoice_number }}</h1>
    <p class="muted">
        {{ __('Issued') }} {{ $invoice->created_at?->toDateString() }}
        @if($invoice->due_date) · {{ __('Due') }} {{ $invoice->due_date->toDateString() }} @endif
        · {{ __('Status') }}: {{ $invoice->status }}
    </p>

    <table class="parties"><tr>
        <td>
            <strong>{{ __('From') }}</strong><br>
            {{ $invoice->seller?->name }}<br>
            <span class="muted">{{ $invoice->seller?->email }}</span>
        </td>
        <td>
            <strong>{{ __('To') }}</strong><br>
            {{ $invoice->buyer?->name }}<br>
            <span class="muted">{{ $invoice->buyer?->email }}</span>
        </td>
    </tr></table>

    <table>
        <thead><tr><th>{{ __('Description') }}</th><th class="num">{{ __('Amount') }}</th></tr></thead>
        <tbody>
        @foreach($invoice->items as $item)
            <tr>
                <td>{{ $item->description }}</td>
                <td class="num">{{ $money($item->amount_minor) }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <table class="totals">
        <tr><td>{{ __('Subtotal') }}</td><td class="num">{{ $money($invoice->subtotal_minor) }}</td></tr>
        <tr><td>{{ __('Platform fee') }}</td><td class="num">{{ $money($invoice->fee_minor) }}</td></tr>
        <tr><td>{{ __('Tax') }}</td><td class="num">{{ $money($invoice->tax_minor) }}</td></tr>
        <tr class="grand"><td>{{ __('Total') }}</td><td class="num">{{ $money($invoice->total_minor) }}</td></tr>
    </table>

    <p class="foot">
        {{-- An invoice is a demand, not a receipt. Saying so on the document
             keeps it from being read as proof that money arrived. --}}
        {{ __('This invoice records what is owed. It is not a receipt: a payment is confirmed only when the payment provider tells Vidlix so over a signed webhook.') }}
        <br>{{ __('Generated by Vidlix') }} · {{ now()->toDayDateTimeString() }}
    </p>
</body>
</html>
